version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fusion_resolver
      POSTGRES_USER: fusion
      POSTGRES_PASSWORD: fusion_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fusion"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  resolver:
    build:
      context: .
      dockerfile: Dockerfile.resolver
    environment:
      - DATABASE_URL=postgresql://fusion:fusion_pass@postgres/fusion_resolver
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
    env_file:
      - .env.local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
  redis_data: